### ISSUE TITLE
Sampler and Scheduler are now separate options. Can you add this? 

### ISSUE THREAD

**Issue by ukharley** [rbbrdckybk/dream-factory#57]
For example you can no longer choose DPM++ 2M karras as it doesn't exist.
Thank you.

**Comment by rbbrdckybk** [comment]
Done!

**Comment by ukharley** [comment]
Thanks for sorting it. Really appreciate it.
I notice though when ADetailer is used you still can't set the scheduler which seems to be causing a warning->
WARNING:root:Sampler Scheduler autocorrection: "Euler" -> "Euler", "None" -> "Automatic"
The sampler is set to DPM++ 2M SDE (can't set the scheduler) so where that's coming from is a mystery. There is also a problem with the Dynamic Prompts extension but Ill open a new issue for that.
